// Generated by CoffeeScript 1.3.3
(function() {

  Crevasse.Previewer = (function() {

    Previewer.prototype.DIALECT = "Gruber";

    Previewer.prototype.PADDING = 20;

    Previewer.prototype.width = null;

    Previewer.prototype.height = null;

    Previewer.prototype.$el = null;

    Previewer.prototype.$offsetDeterminer = null;

    function Previewer(width, height) {
      this.width = width;
      this.height = height;
      this.$el = $("<div class='crevasse_previewer crevasse_reset'>");
      this.$el.css({
        width: this.width - this.PADDING * 2,
        height: this.height - this.PADDING * 2,
        padding: this.PADDING,
        overflow: "scroll"
      });
      this.$offsetDeterminer = this.$el.clone();
      this.$offsetDeterminer.css({
        height: "auto",
        position: "absolute",
        top: 0,
        left: -10000
      });
      return this;
    }

    Previewer.prototype.getEl = function() {
      return this.$el;
    };

    Previewer.prototype.getOffsetDeterminer = function() {
      return this.$offsetDeterminer;
    };

    Previewer.prototype.renderPreview = function(text, caretPosition) {
      var offset;
      offset = this._determineOffset(text.substr(0, caretPosition));
      this.$el.html(markdown.toHTML(text, this.DIALECT));
      if (offset < 0) {
        offset = 0;
      }
      return this.$el.scrollTo(offset, 0);
    };

    Previewer.prototype._determineOffset = function(text) {
      var textHeight;
      this.$offsetDeterminer.html(markdown.toHTML(text, this.DIALECT));
      textHeight = this.$offsetDeterminer.outerHeight();
      return textHeight - this.height / 2;
    };

    return Previewer;

  })();

}).call(this);
